name: Mypy check

on:
  pull_request:
  push:
    branches: master


jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Tox
        run: pip install tox
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Run Tox
        id: mypy-run
        run: tox -e mypy
        continue-on-error: true
      - name: Report if mypy has gone wrong.
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '*Warning*: The **mypy** type checker has found some errors. See the mypy job for details'
            })
        if: steps.mypy-run.outcome == 'failure'
