name: Tox tests

on: [push, pull_request]

jobs:
  py39:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py39
  py310:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py310
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e static
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e cov
      - name: Install pytest cov
        run: pip install pytest-cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true  
